### ISSUE TITLE
Notebook v4.3.1 enabled xsrf

### ISSUE THREAD

**Issue by lgpage** [jupyter/nbgrader#592]
Need to update `ajax` calls to send the xsrf token in the X-XSRF-Token header. This is currently causing CI builds to fail.

Example [here](https://github.com/jupyter/notebook/blob/4.x/notebook/static/base/js/utils.js#L702) for how the notebook js does it.

**Comment by lgpage** [comment]
See also: https://blog.jupyter.org/2016/12/21/jupyter-notebook-4-3-1/#updatepracticaleffectsofxsrfforextensions

**Comment by minrk** [comment]
Perhaps a bit of a hack, but 4.3.1 introduces a `utils.ajax` that does the same thing as `$.ajax`, ensuring the xsrf header is added, so you could probably get away with:

```javascript
var ajax = utils.ajax || $.ajax;
```

which would use the xsrf-including ajax function if defined (`>= 4.3.1`), or the base `$.ajax` if not.

**Comment by lgpage** [comment]
Nifty and easy enough to update for. Thanks.

**Comment by minrk** [comment]
That's precisely why I did it, so my find-replace throughout the notebook codebase would be easy (`s/$.ajax/utils.ajax/`). The benefit should be the same for others as well, I suppose.

**Comment by magsol** [comment]
I'm actually running into this error now whenever students of mine are trying to fetch assignments. On the UI end, it just says "Error fetching assignment"; in the JupyterHub logs, I'm seeing this:

```
[W 2017-01-12 11:42:34.458 user123 web:1545] 403 POST /user/user123/assignments/fetch (::ffff:172.21.31.151): '_xsrf' argument missing from POST
[W 2017-01-12 11:42:34.460 user123 log:47] 403 POST /user/user123/assignments/fetch (::ffff:172.21.31.151) 2.03ms referer=https://jupyterhub.cs.uga.edu/user/user123/tree?
```

Would the fix be to upgrade nbgrader to 0.4.0?

**Comment by lgpage** [comment]
@magsol can you try the `v0.3.2` release, it should fix this.

**Comment by magsol** [comment]
@lgpage Since I'm already in a running environment (classes began a week ago), would an in-place upgrade nuke anything? Since it's a minor upgrade (0.3.1 to 0.3.2) I assume it should be pretty easy.

**Comment by lgpage** [comment]
@magsol it shouldn't nuke anything, the changes from `0.3.1` to `0.3.2` were for the `notebook v4.3` update and for fixing build tests effected thereby.

**Comment by magsol** [comment]
@lgpage Unfortunately still getting the same error. Can confirm I'm now on `0.3.2`, but after restarting the JupyterHub server, still getting the same 403 errors in the JupyterHub logs when attempting to fetch the assignments. Passing `xsrf_cookies: False` into the `c.JupyterHub.tornado_settings` dictionary seems to have no effect, either.

**Comment by lgpage** [comment]
@magsol you may also need to reinstall the `assignment_list` nbextension.

**Comment by magsol** [comment]
Just put that together two seconds before your post came in--works like a charm now. Thank you very much! :)
